### ISSUE TITLE
`CFDataset.ensemble_member` does not check passthrough attrs

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/nchelpers#9]
The `CFDataset` class [exposes a derived property](https://github.com/pacificclimate/nchelpers/blob/master/nchelpers/__init__.py#L511) named `ensemble_member`. This property is composed of several global attributes that are *supposed* to be present in the underlying NetCDF file. However, the code doesn't actually check for these attributes. So trying to access this property results in obscure and non-descriptive error messages. For example:

```bash
$ python `/usr/bin/which generate_climos.py` -n -s -g -o processed/ 5var_day_MIROC3.2_B1_run1_19500101-20991231.nc
```
...
```python
Traceback (most recent call last):
  File "/local_temp/hiebert/env/bin/generate_climos.py", line 372, in <module>
    main(args)
  File "/local_temp/hiebert/env/bin/generate_climos.py", line 342, in main
    climo_output_filepath(args.outdir, input_file, datetime.now(), datetime.now(), variable='var')
  File "/local_temp/hiebert/env/bin/generate_climos.py", line 319, in climo_output_filepath
    return os.path.realpath(os.path.join(output_dir, input_file.climo_output_filename(t_start, t_end, **kwargs)))
  File "/local_temp/hiebert/env/lib/python3.5/site-packages/nchelpers/__init__.py", line 630, in climo_output_filename
    time_range=_cmor_formatted_time_range(t_start, t_end)
  File "/local_temp/hiebert/env/lib/python3.5/site-packages/nchelpers/__init__.py", line 544, in _cmor_type_filename_components
    'ensemble_member': self.ensemble_member,
  File "netCDF4/_netCDF4.pyx", line 2430, in netCDF4._netCDF4.Dataset.__getattr__ (netCDF4/_netCDF4.c:21275)
  File "netCDF4/_netCDF4.pyx", line 2375, in netCDF4._netCDF4.Dataset.getncattr (netCDF4/_netCDF4.c:20234)
  File "netCDF4/_netCDF4.pyx", line 1114, in netCDF4._netCDF4._get_att (netCDF4/_netCDF4.c:4520)
AttributeError: NetCDF: Attribute not found
```

At least one can tell that this is a missing attribute problem. But the netCDF C library doesn't tell you *which* attribute, which isn't super useful.

The Python code should catch this before it makes the underlying C calls and raise a proper ``AttributeError``.

**Comment by rod-glover** [comment]
Fixed in https://github.com/pacificclimate/nchelpers/pull/12
